# Generated by Django 5.2.14 on 2026-06-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['name'], 'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('name', 'department')},
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['name', 'department', 'type', 'salary', 'vacancy', 'is_active'], name='hr_position_name_806483_idx'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.CheckConstraint(condition=models.Q(('salary__gte', 0)), name='salary_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.CheckConstraint(condition=models.Q(('vacancy__gte', 0)), name='vacancy_gte_0'),
        ),
    ]
